{"code": 0, "msg": "FAIL", "task_id": "2022082301390177871015", "task_name": "whole process", "create_time": "20220823013901778766", "error": "Traceback (most recent call last):\n  File \"/home/jit/service/mpc/Compiler/instructions_base.py\", line 848, in check_args\n    ArgFormats[f].check(arg)\n  File \"/home/jit/service/mpc/Compiler/instructions_base.py\", line 672, in check\n    util.format_trace(arg.caller))\nCompiler.exceptions.ArgumentError: (s6, 'Register from other tape, trace: <omitted>')\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/jit/service/mpc/Compiler/types.py\", line 5378, in assign\n    other.store_in_mem(self.get_address(base, other.size))\n  File \"/home/jit/service/mpc/Compiler/types.py\", line 4004, in store_in_mem\n    self.v.store_in_mem(address)\n  File \"/home/jit/service/mpc/Compiler/types.py\", line 2407, in store_in_mem\n    self._store_in_mem(address, stms, stmsi)\n  File \"/home/jit/service/mpc/Compiler/types.py\", line 202, in instruction_typed_operation\n    res = operation(self, *args, **kwargs)\n  File \"/home/jit/service/mpc/Compiler/types.py\", line 670, in _store_in_mem\n    direct_inst(self, address)\n  File \"/home/jit/service/mpc/Compiler/instructions_base.py\", line 395, in maybe_gf2n_instruction\n    return instruction(*args, **kwargs)\n  File \"/home/jit/service/mpc/Compiler/instructions_base.py\", line 304, in maybe_vectorized_instruction\n    return Vectorized_Instruction(size, *args, **kwargs)\n  File \"/home/jit/service/mpc/Compiler/instructions_base.py\", line 268, in __init__\n    super(Vectorized_Instruction, self).__init__(*args, **kwargs)\n  File \"/home/jit/service/mpc/Compiler/instructions_base.py\", line 1091, in __init__\n    super(DirectMemoryWriteInstruction, self).__init__(*args, **kwargs)\n  File \"/home/jit/service/mpc/Compiler/instructions_base.py\", line 1071, in __init__\n    super(DirectMemoryInstruction, self).__init__(*args, **kwargs)\n  File \"/home/jit/service/mpc/Compiler/instructions_base.py\", line 809, in __init__\n    self.check_args()\n  File \"/home/jit/service/mpc/Compiler/instructions_base.py\", line 851, in check_args\n    % (n, e.arg, self) + '\\n' + e.msg)\nCompiler.exceptions.CompilerError: Invalid argument 0 \"s6\" to instruction: vstms 2, s6, 8207\nRegister from other tape, trace: <omitted>\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/jit/service/mpc/Compiler/instructions_base.py\", line 848, in check_args\n    ArgFormats[f].check(arg)\n  File \"/home/jit/service/mpc/Compiler/instructions_base.py\", line 672, in check\n    util.format_trace(arg.caller))\nCompiler.exceptions.ArgumentError: (s6, 'Register from other tape, trace: <omitted>')\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/jit/service/mpc/driver/task.py\", line 60, in persist\n    r = self.__future.result()\n  File \"/usr/lib/python3.6/concurrent/futures/_base.py\", line 425, in result\n    return self.__get_result()\n  File \"/usr/lib/python3.6/concurrent/futures/_base.py\", line 384, in __get_result\n    raise self._exception\n  File \"/usr/lib/python3.6/concurrent/futures/thread.py\", line 56, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/home/jit/service/mpc/SrcCode/main_dynamic_function.py\", line 30, in start_mpc\n    res = dv.eval_formula()\n  File \"/home/jit/service/mpc/SrcCode/Source/dynamic_function.py\", line 235, in eval_formula\n    vars[j] = self.names[inputs[j]]\n  File \"/home/jit/service/mpc/Compiler/types.py\", line 5721, in __setitem__\n    self[index].assign(other)\n  File \"/home/jit/service/mpc/Compiler/types.py\", line 5388, in assign\n    self[base + i] = j\n  File \"/home/jit/service/mpc/Compiler/types.py\", line 5301, in __setitem__\n    self._store(value, self.get_address(index))\n  File \"/home/jit/service/mpc/Compiler/types.py\", line 5349, in _store\n    self.value_type.conv(value).store_in_mem(address)\n  File \"/home/jit/service/mpc/Compiler/types.py\", line 4004, in store_in_mem\n    self.v.store_in_mem(address)\n  File \"/home/jit/service/mpc/Compiler/types.py\", line 2407, in store_in_mem\n    self._store_in_mem(address, stms, stmsi)\n  File \"/home/jit/service/mpc/Compiler/types.py\", line 202, in instruction_typed_operation\n    res = operation(self, *args, **kwargs)\n  File \"/home/jit/service/mpc/Compiler/types.py\", line 670, in _store_in_mem\n    direct_inst(self, address)\n  File \"/home/jit/service/mpc/Compiler/instructions_base.py\", line 395, in maybe_gf2n_instruction\n    return instruction(*args, **kwargs)\n  File \"/home/jit/service/mpc/Compiler/instructions_base.py\", line 302, in maybe_vectorized_instruction\n    return instruction(*args, **kwargs)\n  File \"/home/jit/service/mpc/Compiler/instructions_base.py\", line 1091, in __init__\n    super(DirectMemoryWriteInstruction, self).__init__(*args, **kwargs)\n  File \"/home/jit/service/mpc/Compiler/instructions_base.py\", line 1071, in __init__\n    super(DirectMemoryInstruction, self).__init__(*args, **kwargs)\n  File \"/home/jit/service/mpc/Compiler/instructions_base.py\", line 809, in __init__\n    self.check_args()\n  File \"/home/jit/service/mpc/Compiler/instructions_base.py\", line 851, in check_args\n    % (n, e.arg, self) + '\\n' + e.msg)\nCompiler.exceptions.CompilerError: Invalid argument 0 \"s6\" to instruction: stms s6, 8207\nRegister from other tape, trace: <omitted>\n"}